{% set name = "conda-store" %}
{% set version = "2024.3.1" %}

package:
  name: {{ name|lower }}-split
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/c/conda-store/conda_store-{{ version }}.tar.gz
    sha256: 9a5cef4d45b106889cc127a316236dcb7be577566bb0b81e0fb57bdb251a18c8
    folder: conda-store
  - url: https://pypi.io/packages/source/c/conda-store-server/conda_store_server-{{ version }}.tar.gz
    sha256: 3c2eb332749a1580be479e609485aec6d27168ed0c6aa01c7d057bb8ccd405d8
    folder: conda-store-server

build:
  number: 0

outputs:
  - name: conda-store
    version: {{ version }}
    build:
      noarch: python
      skip: true  # [not linux]
    script: build_conda_store.sh
    requirements:
      host:
        - python >=3.8
        - pip
      run:
        - aiohttp
        - click
        - python >=3.8
        - rich
        - ruamel.yaml
        - yarl
      run_constrained:
        - {{ pin_subpackage('conda-store-server', min_pin='x.x.x', max_pin='x.x.x') }}

    test:
      imports:
        - conda_store
      commands:
        - conda-store --help

  - name: conda-store-server
    version: {{ version }}
    build:
      noarch: python
    script: build_conda_store_server.sh
    requirements:
      host:
        - python >=3.8
        - pip
      run:
        - alembic
        - celery
        - conda
        - conda-docker  # [linux]
        - __linux  # [linux]
        - __osx    # [osx]
        - conda-pack
        - fastapi
        - filelock
        - itsdangerous
        - jinja2
        - minio
        - pydantic <2.0a0
        - pyjwt
        - python >=3.8
        - python-docker
        - python-multipart
        - pyyaml
        - redis-py
        - requests
        - sqlalchemy
        - traitlets
        - uvicorn
        - yarl
      run_constrained:
        - {{ pin_subpackage('conda-store', min_pin='x.x.x', max_pin='x.x.x') }}

    test:
      imports:
        - conda_store_server
      commands:
        - conda-store-server --help
        - conda-store-worker --help

about:
  home: https://github.com/Quansight/conda-store
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Conda Environment Management, Builds, and Serve
  description: |
    End users think in terms of environments not packages. The core
    philosophy of conda-store is to serve identical conda environments
    in as many ways as possible. Conda Store controls the environment
    lifecycle: management, builds, and serving of environments.
  doc_url: https://conda-store.readthedocs.io/
  dev_url: https://github.com/Quansight/conda-store

extra:
  feedstock-name: conda-store
  recipe-maintainers:
    - trallard
    - costrouc
    - jaimergp
