{% set name = "conda-store" %}
{% set version = "2025.2.2" %}
{% set python_min = "3.10" %}


package:
  name: {{ name|lower }}-split
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/c/conda-store/conda_store-{{ version }}.tar.gz
    sha256: f2039e8a5b61c76094f7245981772dda1a11624d70278784f4af7be270b9bc18
    folder: conda-store
  - url: https://pypi.org/packages/source/c/conda-store-server/conda_store_server-{{ version }}.tar.gz
    sha256: 898a5ff25dd871a86ad8345e50318253940879f1ee2ab0207f10492ad819b6cb
    folder: conda-store-server

build:
  number: 0

outputs:
  - name: conda-store
    version: {{ version }}
    build:
      noarch: python
      script: python -m pip install ./conda-store -vv --no-deps --no-build-isolation --no-index
      entry_points:
        - conda-store = conda_store.__main__:main
    requirements:
      host:
        - python {{ python_min }}
        - pip
        - hatchling >=1.14.0
        - hatch-vcs
      run:
        - __linux  # [linux]
        - __osx    # [osx]
        - __win    # [win]
        - aiohttp >=3.8.1
        - click
        - python >={{ python_min }}
        - rich
        - ruamel.yaml
        - yarl
      run_constrained:
        - {{ pin_subpackage('conda-store-server', min_pin='x.x.x', max_pin='x.x.x') }}

    test:
      requires:
        - pip
        - python {{ python_min }}
      imports:
        - conda_store
      commands:
        - pip check
        - conda-store --help

  - name: conda-store-server
    version: {{ version }}
    build:
      noarch: python
      script: python -m pip install ./conda-store-server -vv --no-deps --no-build-isolation --no-index
      entry_points:
        - conda-store-server = conda_store_server._internal.server.__main__:main
        - conda-store-worker = conda_store_server._internal.worker.__main__:main
    requirements:
      host:
        - python {{ python_min }}
        - pip
        - hatchling >=1.14.0
        - hatch-vcs
      run:
        - alembic
        - celery
        - conda
        - conda-docker  # [linux]
        - __linux  # [linux]
        - __osx    # [osx]
        - __win    # [win]
        - conda-pack
        - conda-lock
        - constructor
        - fastapi
        - filelock
        - itsdangerous
        - jinja2
        - minio
        - pydantic >=2.0
        - pyjwt
        - python >={{ python_min }}
        - python-docker
        - python-multipart
        - pyyaml >=6.0.1
        - redis-py
        - requests
        # setuptools>=70 uses local version of packaging (and other deps) without
        # pinning them; conda-lock depends on this, but also doesn't pin the setuptools
        # version. See https://github.com/pypa/setuptools/issues/4478 for details
        - setuptools<70
        - sqlalchemy >=2.0,<2.1
        - traitlets
        - uvicorn
        - yarl
        - psycopg2
        - psycopg2-binary
        - pymysql
      run_constrained:
        - {{ pin_subpackage('conda-store', min_pin='x.x.x', max_pin='x.x.x') }}

    test:
      requires:
        - pip
        - python {{ python_min }}
      imports:
        - conda_store_server
      commands:
        - pip check
        - conda-store-server --help
        - conda-store-worker --help

about:
  home: https://github.com/conda-incubator/conda-store
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Conda Environment Management, Builds, and Serve
  description: |
    End users think in terms of environments not packages. The core
    philosophy of conda-store is to serve identical conda environments
    in as many ways as possible. Conda Store controls the environment
    lifecycle: management, builds, and serving of environments.
  doc_url: https://conda.store/
  dev_url: https://github.com/conda-incubator/conda-store

extra:
  feedstock-name: conda-store
  recipe-maintainers:
    - peytondmurray
    - soapy1
    - trallard
    - jaimergp
